# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Elton's Blog
email:
description: >- # this means to ignore newlines until "baseurl:"
  Notes from the field of freelance IT consultant and trainer Elton Stoneman - 
  14x Microsoft MVP, Docker Captain and author for Pluralsight and Manning.
twitter_username: eltonstoneman
github_username: sixeyed
minimal_mistakes_skin: default
search: true

url: https://blog.sixeyed.com
repository: sixeyed/blog-sixeyed-com

paginate: 5 # amount of posts to show
paginate_path: /page/:num/

atom_feed:
  path: /rss

feed:
  path: /rss

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Elton Stoneman"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Freelance consultant and trainer. 14x Microsoft MVP. Manning Author. Pluralsight Author. "
  uri: https://www.pluralsight.com/authors/elton-stoneman
  github: sixeyed
  twitter: EltonStoneman
  links:
    - label: "Pluralsight"
      icon: "a-fw fa-regular fa-circle-play"
      url: "https://www.pluralsight.com/authors/elton-stoneman"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/EltonStoneman"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sixeyed"

footer:
  links:
    - label: "Pluralsight"
      icon: "fa-fw fa-regular fa-circle-play"
      url: "https://www.pluralsight.com/authors/elton-stoneman"
    - label: "Udemy"
      icon: "fa-fw fa-regular fa-circle-play"
      url: "https://docker4.net/udemy"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/EltonStoneman"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eltonstoneman/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sixeyed"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@EltonStoneman"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_sticky: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "content/images"
    values:
      image: true

tag_archive:
  type: liquid
  path: /tags/

minimal_mistakes_skin: "mint"
enable_copy_code_button: true
repository: "sixeyed/blog-sixeyed-com"

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
